(test (alist nil)     t)
(test (alist '(a))    t)
(test (alist '(a b))  t)
(test (alist 'foo)    nil)
(test (alist car)     nil)
(test (alist 123)     nil)
(test (alist "abc")   nil)
(test (alist #\A)     nil)
(test (alist (table)) nil)
