(test (if)                     nil)
(test (if 1)                   1)
(test (if nil 1)               nil)
(test (if t 1)                 1)
(test (if nil 1 2)             2)
(test (if t 1 2)               1)
(test (if nil 1 t 2)           2)
(test (if nil 1 nil 2)         nil)
(test (if nil 1 nil 2 3)       3)
(test (if nil 1 nil 2 nil 3)   nil)
(test (if nil 1 nil 2 t 3)     3)
(test (if nil 1 nil 2 nil 3 4) 4)
